---
title: "Build a GTAP database with land use split in subnational bounds"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{raster_processing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, eval = FALSE}
## It's come here.

```

```{r, eval = FALSE}
devtools::document("gtapshape")
require(dplyr)
```
## Inputs:
```{r, eval = FALSE}
subnat_bound_file = "C:/Users/nvill/Dropbox/papers/Current/GTAPBIOMES_shared/GTAP_BIOMES/raw_data/beefORsoy_75%_cutoff_sf.rds"
year = "2017"

## Make a gridded dataframe from the SF file with subnational
## boundaries:
##  g <- make_subnatbound_gridded_dataframe(subnat_bound_file)
g <- make_subnatbound_gridded_dataframe() ## Default is aez18

## Annual national data, from FAOSTAT (4-letters data labels are used
## later for compatibility with the har file):
year = "2017"
iso.data <- list(
    QCR8 = iso.crop.production.2011.2022[
        iso.crop.production.2011.2022$year==year,],
    VCR8 = iso.crop.outputvalue.2011.2022[
        iso.crop.outputvalue.2011.2022$year==year,],
    HARV = iso.crop.harea.2011.2022[
        iso.crop.harea.2011.2022$year==year,],
    QLV3 = iso.gsc3lstk.heads.2011.2022[
        iso.gsc3lstk.heads.2011.2022$year==year,],
    VLV3 =iso.gsc3lstk.outputvalue.2011.2022[
        iso.gsc3lstk.outputvalue.2011.2022$year==year,],
    LAND = iso.land.cover.2011.2022[iso.land.cover.2011.2022$year==year,]
)

## Description of each dataset, used later when producing the har file:
attr(iso.data$QCR8, 'description')= 'Crop production (MT) for the 8 gtap crops'
attr(iso.data$VCR8, 'description')= 'Value of crop production (1000 USD) for the 8 gtap crops'
attr(iso.data$HARV, 'description')= 'Harvested area (ha) for the 8 gtap crops'
attr(iso.data$QLV3, 'description')= 'Livestock production (heads) for the 3 gtap livestock sectors'
attr(iso.data$VLV3, 'description')= 'Livestock output value (1000 USD) for the 3 gtap livestock sectors'
attr(iso.data$LAND, 'description')= 'Land cover areas (ha)'


```

## Subnational bound shares of ag. production or and land cover used to share:

```{r, eval = FALSE}
file.names.list <- list(
    crops = gridded.output.file.names <- list.files(system.file("monfreda", package = "gtapshape"),
                                            pattern = "\\Production.rda$", full.names = TRUE
                                            ),
    lstck = gridded.livestock.file.names <- c(
        system.file("fao_lstck_2005", "cattle.rda", package = "gtapshape"),
        system.file("fao_lstck_2005", "goats.rda", package = "gtapshape"),
        system.file("fao_lstck_2005", "sheep.rda", package = "gtapshape")),
    cover = gridded.landcover.file.names <- list.files(
        system.file("land_cover_2000", package = "gtapshape"),
        pattern = "\\.rda$", full.names = TRUE)
)

system.time( ## user: 78.25   system: 7.35  elapsed 85.84
    subnatbound.use.list <- lapply( file.names.list, function(.f){
        ha.by.iso.subnatbound.6covers <- all_uses_by_subnatbound(
            GADM_subnatbound_df= g,
            gridded.use.file.names= .f)
    }
    )
)

subnatbound.use.list[['crops']] <- merge(subnatbound.use.list[['crops']],
                                         unique(crop.concordance[, c("use", "item_code_cpc")]),
                                         by = "use",
                                         all.x = TRUE
                                         )

subnatbound.use.list[['lstck']] <- full_join(subnatbound.use.list[['lstck']],
                                            gridded.livestock.concordance,
                                            by = c("use"),
                                            relationship="many-to-many")


subnatbound.use.list[['cover']] <- subnatbound.use.list[['cover']] %>%
    dplyr::rename(gsc3=use)

system.time(
    shares <- lapply( subnatbound.use.list, function(.f){
        s <- subnatbound.shares(
            subnatbound.levels= .f,
            sector=if(any(grepl("item_code_cpc", names(.f)))){"item_code_cpc"}else{"gsc3"}
        )
    }
    )
)
```

## Share out national data and aggregate to GTAP sectors:
```{r, eval = FALSE}


## Land use and land cover quantities and values
shares.o <- c(rep("crops",3), rep("lstck", 2), "cover")
system.time( ## user: 5.27   system: 0.05   elapsed:  5.31
    gsc3.by.iso <- lapply(c(1:6), function(.n){
        .i <- iso.data[[.n]]
        .s <- shares.o[[.n]] 
        .l <- sector.by.subnatbound(
            iso.data = .i,
            shares = shares[[.s]],
            units = unique(.i$unit),
            sector = if(any(grepl("item_code_cpc", names(.i)))){"item_code_cpc"}else{"gsc3"}
        )
        ## For the crop variables (production, output value and area
        ## harvested), further aggregation from CPC to GSC3 is needed:
        if( grepl('crops', .s ) ){
            ## Merge and aggregate
            merged <- merge(.l,
                        unique(crop.concordance[, c("item_code_cpc", "gsc3")]),
                        by = "item_code_cpc", all.x = TRUE
                        )
            result <- aggregate(value ~ reg + subnatbound + gsc3,
                                data = merged, sum, na.rm = TRUE)
            ## Add unit
            result$unit <- unique(.l$unit)
            ## Sort the result
            result <- result[order(result$reg, result$subnatbound, result$gsc3), ]
            rownames(result) <- NULL
            .l <- result
        }
        ## Assign attributes for har files:
        attr(.l,'description') <- attr(.i,'description')
        return(.l)
    }
    )
)

names(gsc3.by.iso) <- names(iso.data)


lapply(gsc3.by.iso, function(x) attr(x,'description'))

## Verify number of regions, not tackled.
lapply( gsc3.by.iso, function(.x){
    length(unique(.x$reg))
})

lapply( gsc3.by.iso, function(.x){
    length(unique(.x$subnatbound))
})
```

## Write har file:

```{r, eval = FALSE}

## Prepare data arrays (ordered following the GTAP convention) for
## writing har files:
tohar <- lapply( gsc3.by.iso , function (.i) {
    require(reshape)
    da <- cast( .i, reg ~ subnatbound ~  gsc3, value = 'value' )    
    da[is.na(da)] <- 0
    ## Assign attributes for har files:
    attr(da,'description') <- attr(.i,'description')
    return(da)
}
)

## devtools::install_git('https://github.com/USDA-ERS/MTED-HARr.git')
require(HARr)
write_har(tohar, "test.har")

showConnections()
```
